### ISSUE TITLE
unicode warning

### ISSUE THREAD

**Issue by petiepooo** [zeek/trace-summary#3]
I'm seeing this exception occasionally:

> trace-summary:252: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   if dict == srcs or dict == dsts:

I don't have an example of the line that causes it, though.  My bro-conn logs are being stored as json.

**Comment by jsiwek** [comment]
Thanks for the report.  If you were able to provide an example to reproduce, it's more likely to get addressed.  It at least seems to be only a warning with a sane default behavior/interpretation of what to do there.

**Comment by petiepooo** [comment]
I'm trying to get that for you.  I can't figure out how it's run under SecurityOnion; I tried gunzipping an archived conn log where I see the warning in the summary, then running trace-summary against the log, but I'm not seeing the same numbers as in the archived conn-summary log; nor do I see the warning...
I've instrumented the source and am trying to capture the warning as an exception so I can view the variables being compared..  If it works as I hope, I'll update you when it hits..

**Comment by petiepooo** [comment]
What variables would it be useful to see when I get this warning?  I printed the representations of srcs, dsts, and dict when I get the warning, and get this:
> dict:  [(100.0, u'OTH')]
> srcs:  [(100.0, '\xb2>\x06g')]
> dsts:  [(100.0, '\n\xb4\x01\x01')]

**Comment by petiepooo** [comment]
looks like that source is 178.62.6.103 and dst is 10.180.1.1
I'll look at self and Options and report

**Comment by petiepooo** [comment]
Does this help?
> dict:  [(100.0, u'OTH')]
> srcs:  [(100.0, '\x12\xb8WX')]
> dsts:  [(100.0, '\n\xb4\x14\xdd')]
> Options:  <Values at 0x7f920b812dd0: {'udp': False, 'resolve': True, 'localnets': '/opt/bro/etc/networks.cfg', 'verbose': True, 'topx': 10, 'mintime': 0, 'save_mem': False, 'ilen': 0, 'bytes': False, 'tcp': False, 'sample': 0.01, 'R': None, 'conn_version': 2, 'external': False, 'factor': 100.0, 'conns': True, 'chema': False, 'maxtime': 1e+20, 'storeports': None, 'ports': None, 'excludenets': None}>
> self.\_\_dict\_\_:  {'end': 1555311071.039716, 'srcs': {'\x12\xb8WX': 100.0}, 'dsts': {'\n\xb4\x14\xdd': 100.0}, 'bytes': 1600.0, 'ports': {0: 100.0}, 'states': {u'OTH': 100.0}, 'start': 1555311071.039542, 'updates': 100.0, 'pkts': 100.0, 'servs': {'-': 100.0}, 'frags': 0.0, 'prots': {1: 100.0}, 'payload': 1600.0}

**Comment by jsiwek** [comment]
Thanks.  It looks like there's simple coding mistakes in comparing for value equality instead of object equality.  Can you test the following patch?

```diff
diff --git a/trace-summary b/trace-summary
index 0f1aac5..b11f64d 100755
--- a/trace-summary
+++ b/trace-summary
@@ -220,9 +220,9 @@ class Interval:
                     # Note: 15 is longest possible IPv4 address.
                     oversize = len(item) - 15
                     if oversize > 0:
-                        if dict == srcs:
+                        if dict is srcs:
                             src_over = max(src_over, oversize)
-                        elif dict == dsts:
+                        elif dict is dsts:
                             dst_over = max(dst_over, oversize)
 
             # Increase column widths, if necessary.
@@ -249,7 +249,7 @@ class Interval:
                 for (dict, length) in ((ports, 5), (srcs, srcwidth), (dsts, dstwidth), (servs, 11), (prots, 2), states):
                     try:
                         item = None
-                        if dict == srcs or dict == dsts:
+                        if dict is srcs or dict is dsts:
                             item = inet_ntox(dict[i][1])
                             if Options.resolve:
                                 addrs += [dict[i][1]]
```

**Comment by petiepooo** [comment]
The patch is in.  I'll report back after soaking it for a while.  The warning was occuring about 50% of the time, so I'll plan to check back before the end of week.
Thanks!

**Comment by petiepooo** [comment]
LGTM!
